export const ActionTypes = {
  FETCH_REALTORS_LIST: "FETCH_REALTORS_LIST",
  FETCH_REALTORS_LIST_SUCCESS: "FETCH_REALTORS_LIST_SUCCESS",
  FETCH_REALTORS_LIST_ERROR: "FETCH_REALTORS_LIST_ERROR",
  UPDATE_REALTORS_RATING: "UPDATE_REALTORS_RATING",
  UPDATE_REALTORS_RATING_SUCCESS: "UPDATE_REALTORS_RATING_SUCCESS",
  UPDATE_REALTORS_RATING_ERROR: "UPDATE_REALTORS_RATING_ERROR",
  CREATE_REALTORS_RATING: "CREATE_REALTORS_RATING",
  CREATE_REALTORS_RATING_SUCCESS: "CREATE_REALTORS_RATING_SUCCESS",
  CREATE_REALTORS_RATING_ERROR: "CREATE_REALTORS_RATING_ERROR"
};

export const fetchRealtorsList = payload => ({
  type: ActionTypes.FETCH_REALTORS_LIST,
  payload
});

export const updateRating = payload => ({
  type: ActionTypes.UPDATE_REALTORS_RATING,
  payload
});

export const createRating = payload => ({
  type: ActionTypes.CREATE_REALTORS_RATING,
  payload
});
