export const ActionTypes = {
  SEND_REALTOR_PROFILE: "SEND_REALTOR_PROFILE",
  SEND_REALTOR_PROFILE_SUCCESS: "SEND_REALTOR_PROFILE_SUCCESS",
  SEND_REALTOR_PROFILE_ERROR: "SEND_REALTOR_PROFILE_ERROR",
  EDIT_REALTOR_PROFILE: "EDIT_REALTOR_PROFILE",
  EDIT_REALTOR_PROFILE_SUCCESS: "EDIT_REALTOR_PROFILE_SUCCESS",
  EDIT_REALTOR_PROFILE_ERROR: "EDIT_REALTOR_PROFILE_ERROR"
};

export const sendRealtorProfile = payload => ({
  type: ActionTypes.SEND_REALTOR_PROFILE,
  payload
});

export const editRealtorProfile = payload => ({
  type: ActionTypes.EDIT_REALTOR_PROFILE,
  payload
});
